--
-- PostgreSQL database dump
--

\restrict dXByNcx34953yaBBRD4JHiga22U1QH545UdurP8f4vtUG7TuhplHdGVrkkycu8E

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Bills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Bills" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Type" text NOT NULL,
    "Description" text,
    "Month" text,
    "DueDate" timestamp without time zone,
    "Penalty" numeric(18,2) NOT NULL,
    "Status" text NOT NULL
);


--
-- Name: Bills_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Bills" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Bills_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Bookings" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "FacilityId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Status" text NOT NULL,
    "Purpose" text,
    "Days" integer NOT NULL,
    "TotalPrice" numeric(18,2) NOT NULL,
    "RejectReason" text
);


--
-- Name: Bookings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Bookings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Bookings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Complaints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Complaints" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "ImageUrl" text,
    "Status" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "SocietyId" integer NOT NULL
);


--
-- Name: Complaints_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Complaints" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Complaints_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Events" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "EventDate" timestamp without time zone NOT NULL,
    "Location" text NOT NULL,
    "Organizer" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "SocietyId" integer NOT NULL
);


--
-- Name: Events_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Events" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Events_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Facilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Facilities" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Capacity" integer,
    "Status" text NOT NULL,
    "OperatingHours" text,
    "PricePerDay" numeric(18,2) NOT NULL,
    "SocietyId" integer NOT NULL
);


--
-- Name: Facilities_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Facilities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facilities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Notices" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "SocietyId" integer NOT NULL
);


--
-- Name: Notices_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Notices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Societies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Societies" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Address" text,
    "ContactNumber" text,
    "Amenities" text NOT NULL,
    "Wings" text NOT NULL,
    "Gallery" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


--
-- Name: Societies_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Societies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Societies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "Wing" text,
    "FlatNumber" text,
    "ParkingSlot" text,
    "Profession" text,
    "ProfilePicture" text,
    "ProfilePictureId" text,
    "InvitationToken" text,
    "IsSetup" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "SocietyId" integer NOT NULL
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Bills; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Bills" ("Id", "UserId", "Amount", "Type", "Description", "Month", "DueDate", "Penalty", "Status") FROM stdin;
4	6	123123213213.00	maintenance	\N	hoi	2026-04-22 00:00:00	0.00	pending
3	5	1342.00	maintenance	\N	sdfcwsec	2026-04-11 00:00:00	0.00	paid
\.


--
-- Data for Name: Bookings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Bookings" ("Id", "UserId", "FacilityId", "Date", "Status", "Purpose", "Days", "TotalPrice", "RejectReason") FROM stdin;
1	5	2	2026-04-17 00:00:00	rejected	kasrat karvi chhe	12	2400.00	\N
2	5	2	2026-04-15 00:00:00	approved	kasrat karvi chhe	123	24600.00	\N
\.


--
-- Data for Name: Complaints; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Complaints" ("Id", "UserId", "Title", "Description", "ImageUrl", "Status", "CreatedAt", "SocietyId") FROM stdin;
2	5	aasdf	asdfasdf	https://res.cloudinary.com/dyfa5upsi/image/upload/v1775879754/smartsociety/complaints/c3j927orwfsrwcrbrvwi.jpg	in-progress	2026-04-11 03:55:41.57587	1
\.


--
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Events" ("Id", "Title", "Description", "EventDate", "Location", "Organizer", "CreatedAt", "SocietyId") FROM stdin;
1	fsa	asdf	2026-04-08 09:24:00	asdf	sdfgsadf	2026-04-11 03:54:51.056671	1
\.


--
-- Data for Name: Facilities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Facilities" ("Id", "Name", "Description", "Capacity", "Status", "OperatingHours", "PricePerDay", "SocietyId") FROM stdin;
1	Swimming Pool	Olympic size swimming pool	20	Available	6 AM - 10 PM	500.00	1
2	Fitness Center	Modern equipment with AC	15	Available	5 AM - 11 PM	200.00	1
3	Community Hall	Air-conditioned hall for events	100	Available	8 AM - 11 PM	2000.00	1
\.


--
-- Data for Name: Notices; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Notices" ("Id", "Title", "Description", "Type", "Date", "CreatedAt", "SocietyId") FROM stdin;
\.


--
-- Data for Name: Societies; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Societies" ("Id", "Name", "Address", "ContactNumber", "Amenities", "Wings", "Gallery", "CreatedAt") FROM stdin;
1	Gokuldham Society	borivali ,east 	+91 8320687565	["Swimming Pool","Gymnasium","Club House","24/7 Securityfdsfdfsf"]	[]	["https://res.cloudinary.com/dyfa5upsi/image/upload/v1775880235/smartsociety/gallery/u7wpkzgtr1yx4uiawy4e.jpg","https://res.cloudinary.com/dyfa5upsi/image/upload/v1775880258/smartsociety/gallery/hgopik2qy4iah6d7k2oe.jpg","https://res.cloudinary.com/dyfa5upsi/image/upload/v1775880264/smartsociety/gallery/pc4ljvyhgaudowgc6yxt.jpg","https://res.cloudinary.com/dyfa5upsi/image/upload/v1775880277/smartsociety/gallery/gvkoepn8n61cdy6xb0fd.jpg"]	2026-04-09 05:38:35.519171
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Users" ("Id", "Name", "Email", "PasswordHash", "Role", "Wing", "FlatNumber", "ParkingSlot", "Profession", "ProfilePicture", "ProfilePictureId", "InvitationToken", "IsSetup", "CreatedAt", "SocietyId") FROM stdin;
1	System Admin	admin@society.com	$2a$11$FxxUKu9fdOr4jPZACYCTAuBU0QJvXWX5VqgHGzFHz4KCp2f0vr6rm	admin	\N	\N	\N	\N	https://res.cloudinary.com/dyfa5upsi/image/upload/v1775715108/smartsociety/profiles/nfypxoo9k4tyz4hoamdz.jpg	\N	\N	t	2026-04-09 05:38:36.475238	1
5	dkanzariya172@rku.ac.in	dkanzariya172@rku.ac.in	$2a$11$6jG.Tvvi8ZIeDNm/OFUGKO79b0TkgcHfosq.ZwnWHnYx6BhI9KC5O	resident	A	1023	\N	\N	\N	\N	\N	t	2026-04-11 02:38:17.182286	1
6	ansh	adholakiya398@rku.ac.in	$2a$11$DHgnG137ZgxLeCIuuTiDGOXPqUsYFIRi5p19NsQVA7iwbgnkev4qi	resident	S	132	\N	\N	\N	\N	\N	t	2026-04-11 03:32:35.519655	1
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260411032506_InitialCreatePostgres	10.0.5
20260411032637_UpdateModel	10.0.5
20260411034616_AddRejectReasonToBooking	10.0.5
\.


--
-- Name: Bills_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Bills_Id_seq"', 4, true);


--
-- Name: Bookings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Bookings_Id_seq"', 2, true);


--
-- Name: Complaints_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Complaints_Id_seq"', 2, true);


--
-- Name: Events_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Events_Id_seq"', 1, true);


--
-- Name: Facilities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Facilities_Id_seq"', 4, false);


--
-- Name: Notices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Notices_Id_seq"', 3, false);


--
-- Name: Societies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Societies_Id_seq"', 2, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 6, true);


--
-- Name: Bills PK_Bills; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bills"
    ADD CONSTRAINT "PK_Bills" PRIMARY KEY ("Id");


--
-- Name: Bookings PK_Bookings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id");


--
-- Name: Complaints PK_Complaints; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Complaints"
    ADD CONSTRAINT "PK_Complaints" PRIMARY KEY ("Id");


--
-- Name: Events PK_Events; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "PK_Events" PRIMARY KEY ("Id");


--
-- Name: Facilities PK_Facilities; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Facilities"
    ADD CONSTRAINT "PK_Facilities" PRIMARY KEY ("Id");


--
-- Name: Notices PK_Notices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notices"
    ADD CONSTRAINT "PK_Notices" PRIMARY KEY ("Id");


--
-- Name: Societies PK_Societies; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Societies"
    ADD CONSTRAINT "PK_Societies" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Bills_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Bills_UserId" ON public."Bills" USING btree ("UserId");


--
-- Name: IX_Bookings_FacilityId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Bookings_FacilityId" ON public."Bookings" USING btree ("FacilityId");


--
-- Name: IX_Bookings_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Bookings_UserId" ON public."Bookings" USING btree ("UserId");


--
-- Name: IX_Complaints_SocietyId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Complaints_SocietyId" ON public."Complaints" USING btree ("SocietyId");


--
-- Name: IX_Complaints_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Complaints_UserId" ON public."Complaints" USING btree ("UserId");


--
-- Name: IX_Events_SocietyId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Events_SocietyId" ON public."Events" USING btree ("SocietyId");


--
-- Name: IX_Facilities_SocietyId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Facilities_SocietyId" ON public."Facilities" USING btree ("SocietyId");


--
-- Name: IX_Notices_SocietyId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Notices_SocietyId" ON public."Notices" USING btree ("SocietyId");


--
-- Name: IX_Users_SocietyId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Users_SocietyId" ON public."Users" USING btree ("SocietyId");


--
-- Name: Bills FK_Bills_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bills"
    ADD CONSTRAINT "FK_Bills_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Bookings FK_Bookings_Facilities_FacilityId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT "FK_Bookings_Facilities_FacilityId" FOREIGN KEY ("FacilityId") REFERENCES public."Facilities"("Id") ON DELETE CASCADE;


--
-- Name: Bookings FK_Bookings_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Bookings"
    ADD CONSTRAINT "FK_Bookings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Complaints FK_Complaints_Societies_SocietyId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Complaints"
    ADD CONSTRAINT "FK_Complaints_Societies_SocietyId" FOREIGN KEY ("SocietyId") REFERENCES public."Societies"("Id") ON DELETE RESTRICT;


--
-- Name: Complaints FK_Complaints_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Complaints"
    ADD CONSTRAINT "FK_Complaints_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Events FK_Events_Societies_SocietyId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "FK_Events_Societies_SocietyId" FOREIGN KEY ("SocietyId") REFERENCES public."Societies"("Id") ON DELETE CASCADE;


--
-- Name: Facilities FK_Facilities_Societies_SocietyId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Facilities"
    ADD CONSTRAINT "FK_Facilities_Societies_SocietyId" FOREIGN KEY ("SocietyId") REFERENCES public."Societies"("Id") ON DELETE CASCADE;


--
-- Name: Notices FK_Notices_Societies_SocietyId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notices"
    ADD CONSTRAINT "FK_Notices_Societies_SocietyId" FOREIGN KEY ("SocietyId") REFERENCES public."Societies"("Id") ON DELETE CASCADE;


--
-- Name: Users FK_Users_Societies_SocietyId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Societies_SocietyId" FOREIGN KEY ("SocietyId") REFERENCES public."Societies"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict dXByNcx34953yaBBRD4JHiga22U1QH545UdurP8f4vtUG7TuhplHdGVrkkycu8E

